const ShowRoom=[{
  id:1,
  url:'https://www.americanmusclecarmuseum.com/files/cars/2005-porsche-carrera-gt-16.jpg',
  model:'Porshche Carrera GT',
  specification:'Horsepower: 650 hp',
  price:550000,
  rev:"Icon of a hypercar. The Porshche Engineers in 2004, launched a manual transmission, natural aspirited V10 engine hypercar that still can smoke many other cool cars out in the road. With no stability control this is one of the most dangerous production cars that ever built in the history of car. The very car of Paul Walker's accident which led him to death. Treat this car carefully."
  },
  { id:2,
    url:'http://www.lfmmag.com/wp-content/uploads/2018/03/ring-bros-dodge-charger-defector-1.jpg',
    model:'Dodge Charger 1969',
    specification:'Horsepower: 450 hp',
    price:250000,
    rev:'If you are a car enthusiast then you just can not ignore this classic beauty. This is an iconic American muscle with extreme tunability. We have all seen in the movie Fast and furious how Dom handles this muscle car. A great resource for classic car enthusiasts.'
    },
    { id:3,
      url:'https://www.thesupercarblog.com/wp-content/uploads/2020/02/Pagani-Huayra-BC-Roadster-Blue-Carbon-1000x600.jpg',
      model:'Pagani Huayra',
      specification:'Horsepower: 890 hp',
      price:350000,
      rev:"What makes a stunning hypercar? Is it its cost, reaching in the millions of dollars? Is it the exclusivity, being limited only to a handful of models? Is it the jaw-dropping design, a result of passionate designers given the chance to go all-out? Or is it the immense power generated by an aurally pleasing engine that rumbles to life? Maybe it's the interior, created with the best materials and ripe for customization? Maybe its all of these reasons, plus a little bit of fun."
      },
      { id:4,
        url:'https://i.ytimg.com/vi/jRQZWbpSgNM/maxresdefault.jpg',
        model:'Koenigsseg one:1',
        specification:'Horsepower: 1101 hp',
        price:1150000,
        rev:"Weight to power ratio is 1. The first ever production car to reach this milestone. Swedish car with Swedish technologies and materials, this car is special. One of the most insane car ever made, pushing it to its limit."
        
        },
        { id:5,
          url:'https://www.supercars.net/blog/wp-content/uploads/2016/03/Screenshot-2016-03-11-21.02.29.png',
          model:'Mercedes SL 65 AMG Black Series',
          specification:'Horsepower: 760hp',
          price:450000,
          rev:'German Technologies were always inspired by passion. This car is no different. 5 transmission and a V10 engine is good enough to power this car. With 760 horsepower, this car can go really fast really quick.'
          }
  
  ]
  export default ShowRoom;